all : god.out tortoise.out hare.out reporter.out
	  
god.out 	  : god.cpp
		  		g++ god.cpp -o god.out

tortoise.out  : tortoise.cpp
			    g++ tortoise.cpp -o tortoise.out

hare.out      :	hare.cpp
		   		g++ hare.cpp -o hare.out

reporter.out  : reporter.cpp
			    g++ reporter.cpp -o reporter.out
